Feature/react-router
Vadim-Sakuta-VS/moviedb pull request #5
Opened 2021-04-02 14:47 UTC by Vadim-Sakuta-VS

React Router, added movie details page

2021-04-05 12:50 UTC, vladislav-leh requested changes

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieCard/MovieCard.jsx
> +          <Link to={`/movie/${movie.id}`}>{movie.title}</Link>
Let's add link to the image too

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +const MovieDetailsRow = ({ title, value, children, rowClassAdditional }) => {
Don't create several components in 1 file

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +  const classAdditional = rowClassAdditional || '';
You can use some libs for combining classNames like `clsx`

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +      {resultValue && <Col className='pr-0'>{value || children}</Col>}
Use `resultValue` instead of `value || children`

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +const MovieDetails = ({ match: { params } }) => {
You can use `useParams` hook from react-router instead

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +    return null;
Let's add redirect to 404 if there no id

2021-04-05 12:50 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +  const budget = `${movie.budget}$`;
Why there are two `$` signs?

2021-04-05 14:35 UTC, Vadim-Sakuta-VS commented on src/components/MovieDetails/MovieDetails.jsx
> +  const budget = `${movie.budget}$`;
The second `$` is a sign of currency. API doesn't return type of currency.

2021-04-07 07:43 UTC, vladislav-leh requested changes

2021-04-07 07:43 UTC, vladislav-leh commented on src/components/MovieDetails/MovieDetails.jsx
> +  if (isMounted && !isLoading && !movie.id) {
Not the best solution

2021-04-08 09:17 UTC, Vadim-Sakuta-VS commented
You could to test reviews loading `(show more)` by /movie/299534 route

2021-04-09 09:36 UTC, vladislav-leh requested changes

2021-04-09 09:36 UTC, vladislav-leh commented on src/components/MovieReviews/MovieReviews.jsx
> +    console.log(r);
remove console.log

2021-04-09 09:36 UTC, vladislav-leh commented on src/components/MovieReviews/MovieReviews.jsx
> +    <Row className=''>
remove empty className

2021-04-09 09:43 UTC, vladislav-leh approved these changes

2021-04-09 09:43 UTC, merged